<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="D-N-PC-13103" failures="1" tests="10" name="Command line test" time="4.883" errors="0" timestamp="2023-03-18T15:30:53 IRST">
  <testcase classname="ch07.lifecyclething.FirstLifecycleTest" name="testLifecycle" time="2.747"/>
  <testcase classname="validator.CoordinateTest" name="testInvalidCoordinate" time="0.205">
    <failure type="org.testng.TestException" message="
Method CoordinateTest.testInvalidCoordinate()[pri:0, instance:validator.CoordinateTest@694abbdc] should have thrown an exception of type class javax.validation.ConstraintViolationException">
      <![CDATA[org.testng.TestException: 
Method CoordinateTest.testInvalidCoordinate()[pri:0, instance:validator.CoordinateTest@694abbdc] should have thrown an exception of type class javax.validation.ConstraintViolationException
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testInvalidCoordinate -->
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.25"/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.236"/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.215"/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.25"/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.264"/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.232"/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.199"/>
  <testcase classname="validator.CoordinateTest" name="testValidCoordinate" time="0.258"/>
</testsuite> <!-- Command line test -->
